### ISSUE TITLE
Add a final check after an action has been executed

### ISSUE THREAD

**Issue by deebsman** [prologic/shops#13]
Right now if a check returns false and executes an action, `shops` then assumes the item has passed and moves on. It would be ideal to perform the check again to confirm the action has brought the item into spec.

Example
```
funcs:
  is_file: test -f "$1"

items:
  - name: test shops checking
    check: is_file /tmp/doesnt_exist
    action: echo hi
```

Result
```
  test shops checking ✅ -> hi
```

Expected result
Shops should throw an error since the action has not resolved the check (file still doesn't exist).
